(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "site-lisp" user-emacs-directory))
(add-to-list 'custom-theme-load-path (expand-file-name "themes" user-emacs-directory))

;;; others
(let ((file-name-handler-alist nil))
  (require 'init-eat)
  (require 'init-default)
  (require 'init-utils)
  (require 'init-builtin)
  (require 'init-ui)
  (require 'init-dog)
  (require 'init-edit)
  (require 'init-completion)
  (require 'init-dev)
  (require 'init-windows)
  (when (and eat/enable-icon (display-graphic-p))
    (require 'init-icons))
  (require 'init-app)
  (require 'init-mode)
  (require 'init-org)
  (require 'init-lib)
  (require 'init-mole)
  (require 'init-xterm))
