;;; -*- lexical-binding: t -*-

(eat-package less-theme
  :straight (less-theme :type git :host github :repo "nobiot/less-theme"))

(eat-package nyan-mode :straight t)
(eat-package solaire-mode :straight t)

(eat-package rainbow-mode
  :straight t
  :commands rainbow-mode)

(eat-package nano-theme
  :init
  (setq nano-theme-light/dark 'light
        nano-theme-comment-italic nil
        nano-theme-keyword-italic nil
        nano-theme-system-appearance t))

(eat-package emojify
  :straight t
  :command emojify-mode)

(eat-package doom-themes
  :straight t
  :init
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t
        doom-themes-padded-modeline t
        doom-spacegrey-brighter-comments t
        doom-spacegrey-brighter-modeline t
        doom-spacegrey-comment-bg t)
  :config
  (doom-themes-visual-bell-config)
  (doom-themes-org-config))

(eat-package spacemacs-theme
  :straight t
  :init
  (setq spacemacs-theme-comment-italic t
        spacemacs-theme-keyword-italic t
        spacemacs-theme-org-agenda-height t
        spacemacs-theme-org-bold t
        spacemacs-theme-org-height t
        spacemacs-theme-org-highlight t
        spacemacs-theme-org-priority-bold t
        spacemacs-theme-org-bold t
        spacemacs-theme-underline-parens t))

(eat-package modus-themes
  :straight t
  :init
  (setq modus-themes-slanted-constructs t
        modus-themes-bold-constructs t
        modus-themes-syntax 'green-strings
        modus-themes-no-mixed-fonts t
        modus-themes-paren-match 'intense-bold))

;; Nice window divider
(set-display-table-slot standard-display-table
                        'vertical-border
                        (make-glyph-code ?┃))

(defun +format-mode-line ()
  ;; TODO use -*-FZSuXinShiLiuKaiS-R-GB-normal-normal-normal-*-*-*-*-*-p-0-iso10646-1
  ;; to show flymake or flycheck errors count in mode line
  (let* ((lhs '((:eval (meow-indicator))
                " "
                (:eval (rime-lighter))
                (:eval (propertize (+smart-file-name-cached) 'face 'bold))
                " Row %l Col %C"))
         (rhs '("%m"
                (vc-mode vc-mode)))
         (ww (window-width))
         (lhs-str (format-mode-line lhs))
         (rhs-str (format-mode-line rhs))
         (rhs-w (string-width rhs-str)))
    (format "%s%s%s"
            lhs-str
            (propertize " " 'display `((space :align-to (- (+ right right-fringe right-margin) (+ 1 ,rhs-w)))))
            rhs-str)))

(setq-default header-line-format nil)

(defun +init-ui (&optional frame)
  (if +use-header-line
      (setq-default
       mode-line-format nil
       header-line-format '(:eval (+format-mode-line)))
    (setq-default mode-line-format '(:eval (+format-mode-line))))

  (when (not (display-graphic-p))
    (load-theme +theme-tui t))

  (when (display-graphic-p)
    (load-theme +theme t)

    (eat-package cnfonts
      :straight t
      :init
      (setq cnfonts-use-face-font-rescale t)
      (setq cnfonts-personal-fontnames '(("Monaco")("FZSuXinShiLiuKaiS-R-GB")()))
      ;; Auto generated by cnfonts
      ;; <https://github.com/tumashu/cnfonts>
      (set-face-attribute
       'default nil
       :font (font-spec :name "-*-Monaco-normal-normal-normal-*-*-*-*-*-m-0-iso10646-1"
                        :weight 'normal
                        :slant 'normal
                        :size 14.0))
      (dolist (charset '(kana han symbol cjk-misc bopomofo))
        (set-fontset-font
         (frame-parameter nil 'font)
         charset
         (font-spec :name "FZSuXinShiLiuKaiS-R-GB"
                    :weight 'normal
                    :slant 'normal
                    :size 16.5))))
    (set-fontset-font t 'unicode +font-unicode nil 'prepend)
    (set-fontset-font t 'symbol (font-spec :family +font-unicode) frame 'prepend)
    (set-face-attribute 'variable-pitch frame :font +font-variable-pitch :height +font-height)
    ;; HACK use cnfongs
    ;; (set-face-attribute 'default frame :font +font :height +font-height)
    ;; (set-fontset-font t '(#x4e00 . #x9fff) +font-cn)
    ;; (set-frame-font +font nil (if frame (list frame) t))
    ;; (set-face-attribute 'fixed-pitch frame :font +font :height +font-height)

    (eat-package ligature
      :straight (ligature :type git :host github :repo "mickeynp/ligature.el")
      :require t
      :config
      (global-ligature-mode)
      ;; https://htmlpreview.github.io/?https://github.com/kiliman/operator-mono-lig/blob/master/images/preview/normal/index.html
      (ligature-set-ligatures 'prog-mode
                              '("&&" "||" "|>" ":=" "==" "===" "==>" "=>"
                                "=<<" "!=" "!==" ">=" ">=>" ">>=" "->" "--"
                                "-->" "<|" "<=" "<==" "<=>" "<=<" "<!--" "<-"
                                "<->" "<--" "</" "+=" "++" "??" "/>" "__" "WWW")))))

(defun +reload-ui-in-daemon (frame)
  "Reload the modeline and font in an daemon frame."
  (with-selected-frame frame
    (+init-ui frame)))

;; Load the modeline and fonts
(if (daemonp)
    (add-hook 'after-make-frame-functions #'+reload-ui-in-daemon)
  (+init-ui))

(provide 'init-ui)
