;;; -*- lexical-binding: t -*-

(straight-use-package 'pretty-hydra)

(defun +change-theme (theme)
  "Disable other themes and load new one"
  (interactive)
  (mapc #'disable-theme custom-enabled-themes)
  (load-theme theme t))

;;; pretty-hydra
(pretty-hydra-define toggles-hydra (:title "Toggles" :quit-key "q")
      ("Basic"
       (("n" (if (fboundp 'display-line-numbers-mode)
                 (display-line-numbers-mode (if display-line-numbers-mode -1 1))
               (global-linum-mode (if global-linum-mode -1 1)))
         "line number"
         :toggle (or (bound-and-true-p display-line-numbers-mode) global-linum-mode))
        ("e" electric-pair-mode "electric pair" :toggle t)
        ("c" flyspell-mode "spell check" :toggle t)
        ("s" prettify-symbols-mode "pretty symbol" :toggle t)
        ("b" display-battery-mode "battery" :toggle t)
        ("i" display-time-mode "time" :toggle t)
        ("r" repeat-mode "repeat" :toggle t)
        ("f" follow-mode "follow" :toggle t)
        ("l" +solaire-global-mode "solaire" :toggle t))
       "Highlight"
       (("h l" global-hl-line-mode "line" :toggle t)
        ("h p" show-paren-mode "paren" :toggle t)
        ("h r" rainbow-mode "rainbow" :toggle t)
        ("h d" rainbow-delimiters-mode "delimiter" :toggle t)
        ("h t" global-hl-todo-mode "todo" :toggle t))
       "Program"
       (("F" flymake-mode "flymake" :toggle t)
        ("O" hs-minor-mode "hideshow" :toggle t)
        ("u" subword-mode "subword" :toggle t)
        ("W" which-function-mode "which function" :toggle t)
        ("E" toggle-debug-on-error "debug on error" :toggle (default-value 'debug-on-error))
        ("Q" toggle-debug-on-quit "debug on quit" :toggle (default-value 'debug-on-quit))
        ("v" global-diff-hl-mode "gutter" :toggle t)
        ("V" diff-hl-flydiff-mode "live gutter" :toggle t)
        ("M" diff-hl-margin-mode "margin gutter" :toggle t)
        ("D" diff-hl-dired-mode "dired gutter" :toggle t))
       ;; FIXME
       "Theme"
       (("t s" (+change-theme 'spacemacs-light) "space-light" :toggle t)
        ("t S" (+change-theme 'spacemacs-dark) "space-dark" :toggle t)
        ("t j" (+change-theme 'joker) "joker" :toggle t)
        ("t p" (+change-theme 'printed) "printed" :toggle t)
        ("t b" (+change-theme 'storybook) "storybook" :toggle t)
        ("t d" (+change-theme 'minidark) "minidark" :toggle t)
        ("t m" (+change-theme 'modus-vivendi) "modus-dark" :toggle t)
        ("t M" (+change-theme 'modus-operandi) "modus-light" :toggle t)
        ("t l" (+change-theme 'lazycat-dark) "lazycat-dark" :toggle t)
        ("t L" (+change-theme 'lazycat-light) "lazycat-light" :toggle t)
        ("t o" (+change-theme 'atom-one-dark) "one dark" :toggle t)
        ("t D" (+change-theme 'dracula) "dracula" :toggle t)
        ("t y" (+change-theme 'tao-yin) "yin" :toggle t)
        ("t Y" (+change-theme 'tao-yang) "yang" :toggle t)
        ("t G" (+change-theme 'gotham) "gotham" :toggle t)
        ("t i" (+change-theme 'minimal-dark) "minimal dark" :toggle t)
        ("t I" (+change-theme 'minimal-light) "minimal light" :toggle t)
        ("t n" (+change-theme 'nasy) "nasy" :toggle t))
       "Doom Theme"
       (("d c" (+change-doom-theme 'doom-city-lights) "city-lights" :toggle t)
        ("d o" (+change-doom-theme 'doom-one) "one dark" :toggle t)
        ("d O" (+change-doom-theme 'doom-one-light) "one light" :toggle t)
        ("d t" (+change-doom-theme 'doom-tomorrow-night) "tomorrow night" :toggle t)
        ("d T" (+change-doom-theme 'doom-tomorrow-day) "tomorrow day" :toggle t)
        ("d i" (+change-doom-theme 'doom-Iosvkem) "Iosvkem" :toggle t)
        ("d v" (+change-doom-theme 'doom-vibrant) "vibrant" :toggle t)
        ("d a" (+change-doom-theme 'doom-ayu-mirage) "ayu dark" :toggle t)
        ("d A" (+change-doom-theme 'doom-ayu-light) "ayu light" :toggle t)
        ("d d" (+change-doom-theme 'doom-dracula) "dracula" :toggle t)
        ("d n" (+change-doom-theme 'doom-nord) "nord" :toggle t)
        ("d N" (+change-doom-theme 'doom-nord-light) "nord light" :toggle t)
        ("d s" (+change-doom-theme 'doom-solarized-dark) "solarized dark" :toggle t)
        ("d S" (+change-doom-theme 'doom-solarized-light) "solarized light" :toggle t)
        ("d p" (+change-doom-theme 'doom-spacegrey) "spacegrey" :toggle t)
        ("d z" (+change-doom-theme 'doom-zenburn) "zenburn" :toggle t))))

(pretty-hydra-define tab-bar (:title "Tab Bar" :quit-key "q")
  ("Options"
   (("n" tab-bar-new-tab "New")
    ("r" tab-rename "Rename")
    ("0" tab-bar-close-tab "Close current")
    ("1" tab-bar-close-other "Close other")
    ("u" tab-undo "Undo"))
   "Other Tab"
   (("b" switch-to-buffer-other-tab "Switch buffer")
    ("f" find-file-other-tab "Find file")
    ("d" dired-other-tab "Dired"))
   "Select"
   (("t" tab-bar-select-tab-by-name "Select by name")
    ("l" tab-next "Next Tab")
    ("h" tab-previous "Previous Tab"))))

(global-set-key (kbd "C-x t") 'tab-bar/body)
(global-set-key (kbd "C-h C-h") 'toggles-hydra/body)

(provide 'init-hydra)
